name: Main Tests

on:

  push:

    branches: [ main, master ]

  pull_request:

    branches: [ main, master ]

jobs:

  test:

    timeout-minutes: 60

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code

      uses: actions/checkout@v3

    - name: echo "Running Playwright Tests"

      run: echo "Running Playwright Tests"

    - uses: actions/upload-artifact@v4
